<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>..\..\Program\</OutputPath>
    <DefineConstants>TRACE;DEBUG;ACTIVITY_EDITOR</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\..\Program\</OutputPath>
    <DefineConstants>TRACE;ACTIVITY_EDITOR</DefineConstants>
    <DocumentationFile>..\..\Program\Orts.Formats.OR.xml</DocumentationFile>
    <PlatformTarget>x64</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="GNU.Gettext, Version=1.1.5151.39896, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\3rdPartyLibs\GNU.Gettext.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework, Version=3.6.0.1625, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\3rdPartyLibs\Monogame\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\3rdPartyLibs\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ORTS.Common\ORTS.Common.csproj" />
    <ProjectReference Include="..\ORTS.Content\ORTS.Content.csproj" />
    <ProjectReference Include="..\Orts.Formats.Msts\Orts.Formats.Msts.csproj" />
    <ProjectReference Include="..\Orts.Parsers.Msts\Orts.Parsers.Msts.csproj" />
    <ProjectReference Include="..\Orts.Parsers.OR\Orts.Parsers.OR.csproj" />
  </ItemGroup>
</Project>